application: happiemeter
version: 1
runtime: python27
api_version: 1
threadsafe: false   # set to false if/when running tests

handlers:
- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon\.ico

- url: /test.*
  script: gaeunit.py

- url: /.*
  script: happymeter.application

libraries:
- name: webapp2
  version: latest
- name: django
  version: latest